const NEW_SEARCH = 'NEW_SEARCH';
const LOADING = 'LOADING';
const SILENT_LOADING = 'SILENT_LOADING';
const RESPONSE = 'RESPONSE';
const FINISH_LOADING = 'FINSIH_LOADING';
const NOTHING_FOUND = 'NOTHING_FOUND';
const ERROR = 'ERROR';

export { NEW_SEARCH, LOADING, SILENT_LOADING, RESPONSE, FINISH_LOADING, NOTHING_FOUND, ERROR };
